- src/onnx_ir/_enums.py
Migration of changes in https://github.com/microsoft/onnxscript/pull/2335
> Implement `is_floating_point` on dtypes

- src/onnx_ir/passes/common/constant_manipulation.py
- src/onnx_ir/passes/common/constant_manipulation_test.py
Revert changes to LiftConstantsToInitializersPass because I realized even without variable shadowing, two subgraphs can still define initializers that have the same names in their respective naming scopes. A conflict resolution logic is still needed to ensure initializers coming from different subgraphs do not collide. So I reverted my changes.
> Revert changes to LiftConstantsToInitializersPass

- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
- src/onnx_ir/_graph_containers.py
- src/onnx_ir/passes/common/inliner.py
1. It's now possible to do `node.attributes.add(ir.Attr(...))` to avoid having to get the name as a redundant step.
2. Also allow node attributes to be initialized with a dictionary
- This way users do not have to use
```py
ir.Node(attributes=node.attributes.values())
```
when copying the node. Instead, it is possible to
```py
ir.Node(attributes=node.attributes)
```
3. Implement get_* methods on attributes to make getting default attributes easier.
Before
```py
attr = node.attributes.get("attr")
if attr is not None:
value = attr.as_int()
else:
value = 42
```
now
```py
value = node.attributes.get_int("attr", 42)
```
> Create `add` methods on initializers and attributes

- codecov.yml
Ignore unit tests in coverage reports
> Update codecov.yml to ignore unit tests

- docs/api/core.md
- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
* **Added `to_onnx_text` method**: Introduced a new method in `src/onnx_ir/serde.py` to convert an IR model to ONNX textual representation. The method includes an option to exclude initializers from the output.
* **Extended `from_onnx_text` method**: Enhanced the existing method to support adding initializers to the model during deserialization using a mapping of names to tensors. This addition improves flexibility and usability.
> Support initializers with onnxtext

- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
Suggested by @xiaoyu-work, this PR created convenience methods all_nodes() and subgraphs() for easier access to the nested nodes and subgraphs. They are created so that it is easier to discover the methods.
> Implement all_nodes() and subgraphs() as convenience methods

- src/onnx_ir/_io.py
- src/onnx_ir/external_data.py
This pull request introduces a new feature to the ONNX IR library by adding support for a callback function in several methods. The callback allows users to debug or log information about tensors being saved to external data files (or enable a progress bar). Additionally, minor improvements to code organization and comments are included.
> External data callback and ir.save fixes

- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
- src/onnx_ir/_type_casting.py
- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
4bit tensor unpacking to numpy array was buggy before this fix. I updated the logic to make sure we correctly handle the bytes when converting to numpy.
Added unit tests for all numeric dtypes.
> Fix 4bit tensor unpacking

- src/onnx_ir/tensor_adapters.py
- src/onnx_ir/tensor_adapters_test.py
`torch.float8_e8m0fnu` was added only in PyTorch 2.7. In the `to_torch_dtype` method where we build a dictionary of type mapping from onnx dtypes to torch dtypes, a undefinied member error would be raised if user has a torch version <2.7.
This change conditionally adds the float8_e8m0fnu to the mapping if it is definied in torch. When users request the dtype in an environment that has the older version of PyTorch, an error will be raised to suggest users to upgrade torch version.
> Fix support for torch.float8_e8m0fnu for older versions of PyTorch

- src/onnx_ir/passes/common/naming.py
name_generator was spelled incorrectly.
> Fix a typo in NameFixPass docs

- src/onnx_ir/_core.py
Expose the graph properly in `ir.Function` to make identity comparison easier.
> Expose the graph properly in `ir.Function`

- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
Fix https://github.com/onnx/ir-py/issues/157 by declaring all node output values in a graph first, before constructing the nodes. Previously the model would be incorrectly deserialized with incorrect connections.
Added unit test to guard the behavior.
> Update node deser logic to support out of order subgraphs

- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
- src/onnx_ir/_enums.py
- src/onnx_ir/passes/common/initializer_deduplication.py
- src/onnx_ir/passes/common/initializer_deduplication_test.py
Getting the number of bytes in a string tensor needs special treatment as the STRING data type does not define a bitwidth but needs to be computed from flattening the strings into a sequence of bytes. See call_onnx_api querying .nbytes to temporarily remove large initializers.
String initializers need to be converted to bytes via the .string_data method instead of the .tobytes method in DeduplicateInitializersPass.
Also adds mapping of `np.bytes_` to `STRING` in `DataType.from_numpy`, which was probably just overlooked before, as object and `np.str_` (unicode strings) are already handled. This is related to https://github.com/microsoft/onnxscript/pull/2514
> Support string tensors in DeduplicateInitializersPass and call_onnx_api

- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
Cast attribute values to int or float based on the attribute type when serializing. Otherwise protobuf will complain
> Field onnx.AttributeProto.i: Expected an int, got a boolean. This will be rejected in 7.34.0, please fix it before that
This should fix https://github.com/pytorch/pytorch/issues/161941.
> [serde] Cast attribute values to int or float

- src/onnx_ir/_convenience/__init__.py
- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
Ensure int/float attributes are stored as Python int/float by doing a quick type conversion at Attr initialization. Even though this makes Attr initialization slightly more costly, it allows us to maintain an invariance where an INT or FLOAT value can only be a plain python number, making downstream usage and comparison much easier.
> Ensure int/float attributes are stored as Python int/float

- src/onnx_ir/serde.py
Even though https://onnx.ai/onnx/repo-docs/IR.html#attributes requires the attribute for strings to be utf-8 encoded bytes, custom ops may still store arbitrary data there (see SentencepieceTokenizer in https://github.com/microsoft/onnxruntime-extensions).
This change allows the value to stay in bytes and be reserialized as-is.
Fix #182
> Support deserializing non-utf8 attributes in rare case

- docs/api/core.md
- src/onnx_ir/__init__.py
- src/onnx_ir/_convenience/_constructors.py
- src/onnx_ir/_convenience/_constructors_test.py
A convenience constructor for Value that supports an easier way of supplying arguments.
> Create a convenience constructor for Value

- src/onnx_ir/_core.py
- src/onnx_ir/_core_test.py
- src/onnx_ir/passes/common/naming.py
This pull request enhances the handling of value renaming within the ONNX IR core: When a value (especially an initializer) is renamed, all relevant references—including the graph's initializer dictionary—are consistently updated. This reduces the risk of stale or inconsistent state when manipulating graph initializers.
Key changes:
**Core logic improvements:**
* The `Value` class now ensures that renaming a value also updates the corresponding entry in the graph's `initializers` dictionary, maintaining consistency between the value's name and its registration in the graph. An error is raised if an initializer's name is set to `None`.
* The `__init__` method docstring for `Value` has been updated to document this new behavior, clarifying that renaming a value also updates the graph …
> Update the graph initializers dictionary when renaming Value

- src/onnx_ir/serde.py
- src/onnx_ir/serde_test.py
When the value type is not known, we don't know where to store the shape inside a type proto. This change will make the serializer skip serializing the shape instead of error out.
Fix https://github.com/onnx/ir-py/issues/202
> Handle when the value type is not known when serializing shapes

- src/onnx_ir/_core.py
Previously the dtype was viewed, but an actual dtype conversion needs to happen.
> Fix big endian handling in totypes
